#!/usr/bin/env bash

PATH_TO_CURRENT="/sys/class/backlight/intel_backlight/brightness"
PATH_TO_MAX="/sys/class/backlight/intel_backlight/max_brightness"

MAX=$(<$PATH_TO_MAX)
CURRENT=$(<$PATH_TO_CURRENT)
MIN=0
STEP=30

if [[ $# == 1 && ($1 == "-u" || $1 == "-d") ]]; then
  if [[ $1 == "-u" && $CURRENT -lt $MAX ]]; then
    newb=$(($CURRENT + $STEP))
  fi

  if [[ $1 == "-d" && $CURRENT -gt $MIN ]]; then
    newb=$(($CURRENT - $STEP))
  fi

  echo $newb > $PATH_TO_CURRENT

else
  echo -e "USAGE: sudo backlight [-u|-d]\\n  -u  brightness up\\n  -d  brightness down"
fi
